# Generated by Django 4.2.4 on 2023-08-06 08:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ability",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="", max_length=22, unique=True, verbose_name="название"
                    ),
                ),
            ],
            options={
                "verbose_name": "способность",
                "verbose_name_plural": "способности",
            },
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "назначение",
                "verbose_name_plural": "назначения",
            },
        ),
        migrations.CreateModel(
            name="Challenge",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="", max_length=55, unique=True, verbose_name="описание"
                    ),
                ),
                (
                    "ability",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.ability",
                        verbose_name="проверяемое качество",
                    ),
                ),
            ],
            options={
                "verbose_name": "испытание",
                "verbose_name_plural": "испытания",
            },
        ),
        migrations.CreateModel(
            name="Coach",
            fields=[
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="связанный аккаунт",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "мужчина"), ("F", "женщина")],
                        max_length=1,
                        null=True,
                        verbose_name="пол",
                    ),
                ),
                (
                    "image_width",
                    models.IntegerField(blank=True, verbose_name="ширина картинки"),
                ),
                (
                    "image_height",
                    models.IntegerField(blank=True, verbose_name="высота картики"),
                ),
                (
                    "photo",
                    models.ImageField(
                        height_field="image_height",
                        upload_to="people/",
                        verbose_name="фотография",
                        width_field="image_width",
                    ),
                ),
                (
                    "about",
                    models.TextField(blank=True, default="", verbose_name="о себе"),
                ),
            ],
            options={
                "verbose_name": "тренер",
                "verbose_name_plural": "тренеры",
            },
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="связанный аккаунт",
                    ),
                ),
                (
                    "name_genitive",
                    models.CharField(
                        default="",
                        max_length=250,
                        verbose_name="фамилия и имя в родительном падеже",
                    ),
                ),
                ("birth_date", models.DateField(verbose_name="дата рождения")),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "мужчина"), ("F", "женщина")],
                        max_length=1,
                        null=True,
                        verbose_name="пол",
                    ),
                ),
                (
                    "image_width",
                    models.IntegerField(blank=True, verbose_name="ширина картинки"),
                ),
                (
                    "image_height",
                    models.IntegerField(blank=True, verbose_name="высота картики"),
                ),
                (
                    "photo",
                    models.ImageField(
                        height_field="image_height",
                        upload_to="people/",
                        verbose_name="фотография",
                        width_field="image_width",
                    ),
                ),
                (
                    "about",
                    models.TextField(blank=True, default="", verbose_name="о себе"),
                ),
            ],
            options={
                "verbose_name": "занимающийся",
                "verbose_name_plural": "занимающиеся",
            },
        ),
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="", max_length=22, unique=True, verbose_name="название"
                    ),
                ),
            ],
            options={
                "verbose_name": "место",
                "verbose_name_plural": "места",
            },
        ),
        migrations.CreateModel(
            name="Tier",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(
                        unique=True, verbose_name="номер уровня испытаний"
                    ),
                ),
                (
                    "starting_age",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="минимальный возраст"
                    ),
                ),
                (
                    "boundary_age",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="пограничный возраст"
                    ),
                ),
            ],
            options={
                "verbose_name": "ступень",
                "verbose_name_plural": "ступени",
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="-", max_length=33, unique=True, verbose_name="название"
                    ),
                ),
            ],
            options={
                "verbose_name": "единица измерения",
                "verbose_name_plural": "единицы измерения",
            },
        ),
        migrations.CreateModel(
            name="Training",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        default="Новая", max_length=55, verbose_name="заголовок"
                    ),
                ),
                (
                    "dt",
                    models.DateTimeField(verbose_name="дата и время начала тренировки"),
                ),
                (
                    "duration",
                    models.DurationField(
                        default=datetime.timedelta(seconds=3600),
                        verbose_name="продолжительность тренировки",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="описание"),
                ),
                (
                    "coach_notes",
                    models.TextField(
                        blank=True, default="", verbose_name="замечания тренера"
                    ),
                ),
                (
                    "coach_grade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "отлично"),
                            ("B", "хорошо"),
                            ("C", "удовлетворительно"),
                            ("D", "неудовлетворительно"),
                            ("F", "плохо"),
                        ],
                        max_length=1,
                        null=True,
                        verbose_name="оценка тренера",
                    ),
                ),
                (
                    "member_comment",
                    models.TextField(
                        blank=True, default="", verbose_name="комментарий занимающегося"
                    ),
                ),
                (
                    "completed",
                    models.BooleanField(default=False, verbose_name="завершена"),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.assignment",
                        verbose_name="назначение",
                    ),
                ),
            ],
            options={
                "verbose_name": "тренировка",
                "verbose_name_plural": "тренировки",
            },
        ),
        migrations.CreateModel(
            name="Standard",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "мужчина"), ("F", "женщина")],
                        max_length=1,
                        null=True,
                        verbose_name="пол",
                    ),
                ),
                (
                    "bronze",
                    models.IntegerField(verbose_name="требуемый показатель (бронза)"),
                ),
                (
                    "silver",
                    models.IntegerField(verbose_name="требуемый показатель (серебро)"),
                ),
                (
                    "gold",
                    models.IntegerField(verbose_name="требуемый показатель (золото)"),
                ),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.challenge",
                        verbose_name="испытание",
                    ),
                ),
                (
                    "tier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tier"
                    ),
                ),
            ],
            options={
                "verbose_name": "норматив",
                "verbose_name_plural": "нормативы",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "volume",
                    models.IntegerField(
                        default=0, verbose_name="количество тренировок"
                    ),
                ),
                ("date", models.DateField(verbose_name="дата оплаты")),
                (
                    "image_width",
                    models.IntegerField(blank=True, verbose_name="ширина картинки"),
                ),
                (
                    "image_height",
                    models.IntegerField(blank=True, verbose_name="высота картики"),
                ),
                (
                    "receipt",
                    models.ImageField(
                        height_field="image_height",
                        upload_to="receipts/%Y/%m/",
                        verbose_name="фотография чека",
                        width_field="image_width",
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.assignment",
                        verbose_name="назначение",
                    ),
                ),
            ],
            options={
                "verbose_name": "оплата",
                "verbose_name_plural": "платежи",
            },
        ),
        migrations.CreateModel(
            name="Outcome",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="дата испытания")),
                ("result", models.IntegerField(verbose_name="результат")),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.challenge",
                        verbose_name="испытание",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.member",
                        verbose_name="занимающийся",
                    ),
                ),
            ],
            options={
                "verbose_name": "результат",
                "verbose_name_plural": "результаты",
            },
        ),
        migrations.AddField(
            model_name="challenge",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.unit",
                verbose_name="единица измерения",
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="coach",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.coach",
                verbose_name="тренер",
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.member",
                verbose_name="занимающийся",
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="place",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.place",
                verbose_name="место",
            ),
        ),
    ]